version: "3.14"

services:
    web:
        build: ./apps/web
        container_name: portfolio-web
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - ./apps/web:/home/app
        command: yarn dev
        # env_file:
        #     - ./apps/web/.env
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        healthcheck:
            test: [ "CMD", "lsof", "-t", "-i:3000" ]
            timeout: 10s
            retries: 5
