version: "3.14"

services:
    web:
        build: ./web
        container_name: web-portfolio
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - ./web:/home/app
        command: yarn dev
        env_file:
            - ./web/.env
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        depends_on:
            server:
                condition: service_healthy
        networks:
            - portfolio
        healthcheck:
            test: [ "CMD", "lsof", "-t", "-i:5173" ]
            timeout: 10s
            retries: 5
    server:
        build: ./server
        container_name: server-portfolio
        restart: unless-stopped
        ports:
            - "3002:3002"
            - "9229:9229"
        volumes:
            - ./server:/home/app
        command: yarn debug
        env_file:
            - ./web/.env
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - portfolio
        healthcheck:
            test: [ "CMD", "lsof", "-t", "-i:3002" ]
            timeout: 10s
            retries: 5

networks:
    portfolio:
        driver: "bridge"
