version: "3.14"

services:
    web:
        build: ./apps/web
        container_name: web-portfolio
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - ./apps/web:/home/app
        command: pnpm dev
        env_file:
            - ./apps/web/.env.local
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        depends_on:
            server:
                condition: service_healthy
        networks:
            - portfolio
        healthcheck:
            test: [ "CMD", "lsof", "-t", "-i:3000" ]
            timeout: 10s
            retries: 5
    server:
        build: ./apps/server
        container_name: server-portfolio
        restart: unless-stopped
        ports:
            - "3002:3002"
        volumes:
            - ./apps/server:/home/app
        command: pnpm start:dev
        env_file:
            - ./apps/server/.env.local
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - portfolio
        healthcheck:
            test: [ "CMD", "lsof", "-t", "-i:3002" ]
            timeout: 10s
            retries: 5

networks:
    portfolio:
        driver: "bridge"
