export const NotionDatabase = {
  NOTION_PORTFOLIO_EMAILS_DATABASE_ID:
    process.env.NOTION_PORTFOLIO_EMAILS_DATABASE_ID || '',
  NOTION_PORTFOLIO_PROJECTS_DATABASE_ID:
    process.env.NOTION_PORTFOLIO_PROJECTS_DATABASE_ID || '',
  NOTION_PORTFOLIO_PROJECTS_DATABASE_ID_PT_BR:
    process.env.NOTION_PORTFOLIO_PROJECTS_DATABASE_ID_PT_BR || '',
  NOTION_SKILL_DATABASE_ID: process.env.NOTION_SKILL_DATABASE_ID || '',
  NOTION_SKILLLIST_DATABASE_ID: process.env.NOTION_SKILLLIST_DATABASE_ID || '',
  NOTION_SKILL_DATABASE_ID_PT_BR:
    process.env.NOTION_SKILL_DATABASE_ID_PT_BR || '',
  NOTION_QUALIFICATION_TAB_DATABASE_ID:
    process.env.NOTION_QUALIFICATION_TAB_DATABASE_ID || '',
  NOTION_QUALIFICATION_DATA_DATABASE_ID:
    process.env.NOTION_QUALIFICATION_DATA_DATABASE_ID || '',
  NOTION_QUALIFICATION_TAB_DATABASE_ID_PT_BR:
    process.env.NOTION_QUALIFICATION_TAB_DATABASE_ID_PT_BR || '',
  NOTION_QUALIFICATION_DATA_DATABASE_ID_PT_BR:
    process.env.NOTION_QUALIFICATION_DATA_DATABASE_ID_PT_BR || '',
  NOTION_SERVICE_DATABASE_ID: process.env.NOTION_SERVICE_DATABASE_ID || '',
  NOTION_SERVICE_LIST_DATABASE_ID:
    process.env.NOTION_SERVICE_LIST_DATABASE_ID || '',
  NOTION_SERVICE_DATABASE_ID_PT_BR:
    process.env.NOTION_SERVICE_DATABASE_ID_PT_BR || '',
  NOTION_SERVICE_LIST_DATABASE_ID_PT_BR:
    process.env.NOTION_SERVICE_LIST_DATABASE_ID_PT_BR || '',
  NOTION_MAIN_CONTENT_DATABASE_ID:
    process.env.NOTION_MAIN_CONTENT_DATABASE_ID || '',
};
